data:
  filter_bin_one_is_true: false
train:
  training_args:
    output_dir: models/germeval24/gbert-large/m3
    save_strategy: epoch
    eval_strategy: epoch
    learning_rate: 2e-5
    per_device_train_batch_size: 140
    per_device_eval_batch_size: 140
    num_train_epochs: 15
    logging_dir: logs/germeval24/gbert-large/m3
    # save_total_limit: 1
    # metric_for_best_model: eval_f1
    # load_best_model_at_end: true
    # greater_is_better: true
    report_to: none
    fp16: true
  model_name: deepset/gbert-large
  input_col: text
  label_col: bin_all
  model_labels:
  - all_false
  - all_true